### ISSUE TITLE
Connect to S3 without access and secret key

### ISSUE THREAD

**Issue by jac1013** [laosb/ghos3#4]
I haven't tested this, but it would be nice that `access_key` and `secret_key` were optional and we let the user use IAM roles (or instance profile) to handle the access to S3. This is the recommended practice anyway.

Thoughts?

**Comment by laosb** [comment]
I'm not actually that familiar with AWS S3 since I use DO Spaces / CF R2 most of the time.

Since we are using AWS S3's official SDK, it should supports this. There should be minimal effort for this plugin to adapt that. If you want to take a look to support this and send a PR, I will be very willing to accept & document it.

**Comment by pradeep-dfi** [comment]
For the record, AWS SDK already handles it. Nothing needs to be done. IAM role will be picked up if one is available.
